Monthly Sales Trend (for forecasting prep)

SELECT 
    TO_CHAR(ORDER_DATE, 'YYYY-MM') AS YEAR_MONTH,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES
FROM SUPERSTORE_RAW
GROUP BY YEAR_MONTH
ORDER BY YEAR_MONTH;

