Within each product category, which single product is the most profitable?
SELECT CATEGORY,
       PRODUCT_NAME,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM PORTFOLIO_DB.PUBLIC.SALES_SUPERSTORE
GROUP BY CATEGORY, PRODUCT_NAME
QUALIFY ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY SUM(PROFIT) DESC) = 1
ORDER BY TOTAL_PROFIT DESC;