Regional Contribution to Total Sales

SELECT 
    REGION,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(
        SUM(SALES) / SUM(SUM(SALES)) OVER () * 100, 
        2
    ) AS PERCENT_OF_TOTAL
FROM SUPERSTORE_RAW
GROUP BY REGION
ORDER BY TOTAL_SALES DESC;