Year-Over-Year Sales Growth

SELECT 
    YEAR(ORDER_DATE) AS YEAR,
    ROUND(SUM(SALES), 2) AS TOTAL_SALES,
    ROUND(
        (SUM(SALES) - LAG(SUM(SALES)) OVER (ORDER BY YEAR(ORDER_DATE))) 
        / NULLIF(LAG(SUM(SALES)) OVER (ORDER BY YEAR(ORDER_DATE)), 0) * 100, 
        2
    ) AS YOY_GROWTH_PERCENT
FROM SUPERSTORE_RAW
GROUP BY YEAR(ORDER_DATE)
ORDER BY YEAR;

